import { Inter } from 'next/font/google'

import Link from 'next/link';

import './styles/globals.css'
import AppProvider from './context/context';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'RunPen',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">

      <head><title>runPen</title></head>

      <body className={inter.className}>

        <AppProvider>
          <nav className="bg-dark-green p-4">
            <div className="container mx-4">
              <div className="text-lg text-white font-bold">
                <Link href="/">rP</Link>
              </div>
            </div>
          </nav>

          {children}
        </AppProvider>

      </body>

    </html>
  )
}
