import { Inter } from 'next/font/google'
import './styles/globals.css'

import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'RunPen',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <head><title>runPen</title></head>

      <body className={inter.className}>

        <nav className="bg-pink-500 p-4 text-white">
          <div className="container mx-4">
            <div className="text-lg font-bold">
              <Link href="/">rP</Link>
            </div>
          </div>
        </nav>

        {children}

      </body>
    </html>
  )
}
